# Generated by Django 4.1.2 on 2023-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
    ]
