# Generated by Django 4.1.2 on 2023-04-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
