# Generated by Django 4.1.2 on 2023-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0004_coursematerial_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_materials',
        ),
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='course_materials/'),
        ),
    ]
