# Generated by Django 4.1.2 on 2023-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0005_remove_course_course_materials_course_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.AddField(
            model_name='course',
            name='course_materials',
            field=models.FileField(blank=True, default=None, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='html_content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
