# Generated by Django 4.1.2 on 2023-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0006_remove_course_file_course_course_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_materials',
        ),
        migrations.AddField(
            model_name='course',
            name='course_materials',
            field=models.ManyToManyField(to='photoedit.coursematerial'),
        ),
    ]
