# Generated by Django 4.1.2 on 2023-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0007_remove_course_course_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_materials',
        ),
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(default='default_value', upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='html_content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
