# Generated by Django 4.1.2 on 2023-05-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0012_mycourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoedit.payedcourse'),
        ),
    ]
