# Generated by Django 4.1.2 on 2023-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0013_alter_mycourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoedit.course'),
        ),
    ]
