# Generated by Django 4.2.1 on 2023-05-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0015_remove_course_file_remove_course_html_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('software_icon', models.ImageField(upload_to='free_course_icons/')),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoedit.coursecontent')),
            ],
        ),
    ]
