# Generated by Django 4.2.1 on 2023-05-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0016_freecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecourse',
            name='course_content',
        ),
        migrations.CreateModel(
            name='FCourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoedit.freecourse')),
            ],
        ),
    ]
