# Generated by Django 4.2.1 on 2023-05-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0017_remove_freecourse_course_content_fcoursecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCourseContent',
        ),
        migrations.DeleteModel(
            name='FreeCourse',
        ),
    ]
