# Generated by Django 4.2.1 on 2023-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0018_delete_fcoursecontent_delete_freecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vlogs/')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
