# Generated by Django 4.2.1 on 2023-05-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0021_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
