# Generated by Django 4.2.1 on 2023-05-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0023_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
