# Generated by Django 4.2.1 on 2023-05-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0025_payedcourse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
