# Generated by Django 4.2.1 on 2023-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0026_alter_tutorial_thumbnail_alter_tutorial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
