# Generated by Django 4.2.1 on 2023-05-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoedit', '0028_pcoursecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcoursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoedit.payedcourse'),
        ),
    ]
